// flow-typed signature: 4f27f9143bcf517e0ebc14fac8244c36
// flow-typed version: <<STUB>>/merge_v^1.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'merge/merge' {
  declare module.exports: any;
}

declare module 'merge/merge.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'merge/merge.js' {
  declare module.exports: $Exports<'merge/merge'>;
}
declare module 'merge/merge.min.js' {
  declare module.exports: $Exports<'merge/merge.min'>;
}
